# GitHub Action para gerar um gráfico de contribuição com uma cobra comendo suas contribuições.

nome : Gerar Cobra

# Controla quando a ação será executada. Esta ação ocorre a cada 6 horas.

em :
  horário :
    # a cada 6 horas
    - cron : " 0 * / 6 * * * "

  # Este comando nos permite executar a Ação automaticamente a partir da guia Ações.
  workflow_dispatch :

# A sequência de execuções neste fluxo de trabalho:
empregos :
  # Este fluxo de trabalho contém um único trabalho chamado "build"
  construir :
    # O tipo de executor em que o trabalho será executado
    roda em : ubuntu-mais recente

    # As etapas representam uma sequência de tarefas que serão executadas como parte do trabalho
    passos :

      # Verifica o repo em $ GITHUB_WORKSHOP, para que seu trabalho possa acessá-lo
      - usa : ações / checkout @ v2

      # Gera a cobra
      - usa : Platane / snk @ master
        id : snake-gif
        com :
          github_user_name : mishmanners
          # as próximas 2 linhas geram os arquivos em uma ramificação chamada "output". Isso evita que o branch principal se amontoe.
          gif_out_path : dist / github-Contribution-grid-snake.gif
          svg_out_path : dist / github-Contribution-grid-snake.svg

      # mostra o status da construção. Facilita a depuração (se houver algum problema).
      - run : git status

      # Empurre as mudanças
      - nome : mudanças push
        usa : ad-m / github-push-action @ master
        com :
          github_token : $ {{secrets.GITHUB_TOKEN}}
          ramo : mestre
          força : verdadeiro

      - usa : crazy-max/ghaction-github-pages@v2.1.3
        com :
          # o branch de saída que mencionamos acima
          target_branch : output
          build_dir : dist
        env :
          GITHUB_TOKEN : $ {{secrets.GITHUB_TOKEN}}
